name: geburtstagsliste
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  path_provider: ^2.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  uuid: ^4.2.1
  flutter_slidable: ^3.0.1
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/subject.json
    - assets/event.json
    - assets/images/default_avatar_1.png
  uses-material-design: true
